trigger:
- master

variables:
  BuildConfiguration: Release
  DotnetSdkVersion: '3.1.x'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: $(dotnetSdkVersion)
  displayName: 'Install .NET Core SDK $(DotnetSdkVersion)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c $(BuildConfiguration)'
  displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '-c $(BuildConfiguration) -o $(Build.SourcesDirectory)/publish'
  displayName: 'dotnet publish'

- publish: publish
  artifact: packages
  displayName: 'Publish Artifacts'